# tmux theme: min — near-monochrome low-saturation gray/lavender.
set -g status-style 'bg=#000000,fg=#c4c1c6'
set -g status-left-style 'bg=#171719,fg=#e4e1e6,bold'
set -g status-right-style 'bg=#000000,fg=#e4e1e6'
set -g window-status-current-style 'bg=#68666b,fg=#e4e1e6,bold'
set -g window-status-style 'bg=#000000,fg=#c4c1c6'
set -g window-status-bell-style 'bg=#8c858a,fg=#e4e1e6,bold'
set -g pane-border-style 'fg=#171719'
set -g pane-active-border-style 'fg=#68666b'
set -g message-style 'bg=#211f23,fg=#e4e1e6'
